# Generated by Django 4.2.6 on 2024-01-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_schedule_price_remove_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='email',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
